client_config_backend: settings
client_config:
	client_id: 912830736001-8ne0m4vv87ehjk2cc4u96j5249ofljtu.apps.googleusercontent.com
	client_secret: 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: True
save_credentials_backend: file
save_credentials_file: credentials.jsonget_refresh_token: Trueoauth_scope:
	- https://www.googleapis.com/auth/drive.file